/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;
import javax.swing.JOptionPane;
import newpackage.SQLite;

public class FrmSales extends javax.swing.JFrame {

  
    public FrmSales() {
       

        
         
         initComponents();
        DateFormat dateFormat = new SimpleDateFormat("yy/MM/dd  HH:mm:ss");
        Date date = new Date();
        String ID = dateFormat.format(date);
        txt_id.setText(ID);
        
        setComboBox();
      
    }
    void setComboBox(){

        if(SQLite.openDB()){
            String[][] laptop = SQLite.read("product"," ProductType='Laptop'");
            String[][] ram = SQLite.read("product"," ProductType='RAM'");
            String[][] acce = SQLite.read("product"," ProductType='Accessories'");
            String[][] sd = SQLite.read("product"," ProductType='SD Card'");
            String[][] other = SQLite.read("product"," ProductType='Other'");
            
           int totalProduct = (laptop.length+1) + (ram.length+1)+ (acce.length+1)+ (sd.length+1)
           + (other.length+1)+1 ;
           String[] products = new String[totalProduct];
            int product_index = 0;
            products[product_index] = "";
            product_index++;
            if(laptop.length > 0){
               
                products[product_index] = "----- Laptop -----";  
                product_index++;
                for(int j=0;j<laptop.length;j++){
                    products[product_index] = laptop[j][2];
                    product_index++; 
                }            
                }
               if(ram.length > 0){
                products[product_index] = "----- RAM -----";  
                product_index++;
                for(int j=0;j<ram.length;j++){
                    products[product_index] = ram[j][2];
                    product_index++;
                }  
                }
                if(acce.length > 0){
                products[product_index] = "----- Accessories -----";  
                product_index++;
                for(int j=0;j<acce.length;j++){
                    products[product_index] = acce[j][2];
                    product_index++;
                }
                }
                if(sd.length > 0){
                products[product_index] = "----- SD Card -----";  
                product_index++;
                for(int j=0;j<sd.length;j++){
                    products[product_index] = sd[j][2];
                    product_index++;
                }
                 }
                  if(other.length > 0){
                products[product_index] = "----- Others -----";  
                product_index++;
                for(int j=0;j<other.length;j++){
                    products[product_index] = other[j][2];
                    product_index++;
                }
                }
               
                
                 
                  
                        
            
            
//            products[1] = records[0][2];
//            products[2] = records[1][2];
            
            cmb_product.setModel(new javax.swing.DefaultComboBoxModel(products));
            SQLite.closeDB();
            
            
        }
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Qty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_product = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Cus_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        C_Name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_price = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Date Time ");

        txt_id.setEnabled(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Customer's Name");

        Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Product Name");

        cmb_product.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_product.setMaximumRowCount(12);
        cmb_product.setToolTipText("");
        cmb_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_productActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Quantity");

        Cus_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cus_NameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Price");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Cashier's Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("SALES - Rap Laptop");

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setText("View Sales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_id, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(C_Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Cus_Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_product, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Qty, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_price, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Cus_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QtyActionPerformed

    private void Cus_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cus_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cus_NameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmDisplay Display = new FrmDisplay();
        Display.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
     
        String datetime = txt_id.getText();
        String cashiersName = C_Name.getText();
        String customersName =  Cus_Name.getText();
        String productName = this.cmb_product.getSelectedItem().toString();
        String quantity = Qty.getText();
        
        String price = txt_price.getText();
        
        double total = Double.parseDouble(price)*Double.parseDouble(quantity);
        
     
       
            if(SQLite.openDB()){
                
                String[][] product = SQLite.read("product", " ProductName='"+productName+"'");
                int remainingQty = Integer.parseInt(product[0][3]);
                int orderQty = Integer.parseInt(quantity);
                
                
                if(remainingQty < orderQty){
                    JOptionPane.showMessageDialog(null, "Out of Stock!");
                }
                
                
                else{
                
                    int autoincrement = SQLite.autoincrement("Sales")+1;
                    String values =  "'" +autoincrement + "'"+ "," +"'" +datetime + "'"+ "," + "'" +cashiersName + 
                    "'"  + ","+"'" +customersName+"'"+ " , " + "'" + productName +  "'" + "," + "'" + quantity + "'"+","+ "'" + total + "'";
                   if (SQLite.create("Sales",values)){
                       javax.swing.JOptionPane.showMessageDialog(null, "Sucessfully saved!");
                       
                       // Update Product Quantity
                       int updateQty = remainingQty - orderQty;
                       if(SQLite.update("product", " QTY="+updateQty , " ProductName='"+productName+"'")){
                            javax.swing.JOptionPane.showMessageDialog(null, "Success!");
                       }
                       else{
                            javax.swing.JOptionPane.showMessageDialog(null, "Fields must not left blank");
                       }
                  
                }
                }
                
        
           SQLite.closeDB();
             
    }
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         Main main = new Main();
         main.setVisible(true);
      this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void cmb_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_productActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and FrmDisplay the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSales().setVisible(true);
                }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_Name;
    private javax.swing.JTextField Cus_Name;
    private javax.swing.JTextField Qty;
    private javax.swing.JComboBox<String> cmb_product;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
